[update_manager e3v3p_mainline_update]
type: git_repo
channel: stable
path: /usr/data/e3v3p-update-controller
origin: GITHUB_REPOSITORY_URL
primary_branch: release
is_system_service: True
managed_services: e3v3p_mainline_update
info_tags:
  desc=Validated Ender 3 V3 Plus mainline Klipper host release
